"""Data transfer module will be implemnted"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01_data.transfer.ipynb.

# %% auto 0
__all__ = ['CURRETNT_NB']

# %% ../../nbs/01_data.transfer.ipynb 3
import sys
from pathlib import Path


# %% ../../nbs/01_data.transfer.ipynb 4
#CV_TOOLS = Path(r'/home/ai_dsx.work/data/projects/cv_tools')
#sys.path.append(str(CV_TOOLS))


# %% ../../nbs/01_data.transfer.ipynb 5
#custom_lib_path = Path(r'/home/ai_warstein/homes/goni/custom_libs')
#sys.path.append(str(custom_lib_path))


# %% ../../nbs/01_data.transfer.ipynb 6
#from cv_tools.imports import *
#from cv_tools.core import *
from dotenv import load_dotenv


# %% ../../nbs/01_data.transfer.ipynb 7
#load_dotenv(dotenv_path=f'/home/ai_sintercra/Users/goni/workspace/projects/git_data/be-vision-ad-tools/be-vision-ad-tools/.env')

# %% ../../nbs/01_data.transfer.ipynb 9
CURRETNT_NB='/home/ai_sintercra/Users/goni/workspace/projects/git_data/be-vision-ad-tools/nbs'
