"""Fill in a module description here

Docs: https://HasanGoni.github.io/vision_ad_tool/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['foo']

# %% ../nbs/00_core.ipynb #d73d35cd
def foo(): pass
