"""Hydra-configured CLI entry points.

Docs: https://HasanGoni.github.io/vision_ad_tool/tutorials.end2end_hydra_cli.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/18_tutorials.end2end_hydra_cli.ipynb.

# %% auto #0
__all__ = ['cfg_to_dict', 'run_train', 'run_infer', 'run_organize', 'run_infer_organize', 'run_train_infer', 'run_full',
           'train_cli', 'infer_cli', 'organize_cli', 'infer_organize_cli', 'train_infer_cli', 'full_cli']

# %% ../../nbs/18_tutorials.end2end_hydra_cli.ipynb #03864840
from pathlib import Path
from typing import Any

import hydra
from omegaconf import DictConfig, OmegaConf

from ..inference.anomaly_score_organizer import predict_and_organize_by_score
from ..inference.unified_inference import unified_inference
from ..inference.unified_with_threshold_posters import unified_inference_with_threshold_posters
from ..training.flexible_trainer import FlexibleTrainingConfig, train_anomaly_model, run_inference_after_training


# %% ../../nbs/18_tutorials.end2end_hydra_cli.ipynb #37e9bb3c
def cfg_to_dict(cfg: DictConfig) -> dict[str, Any]:
    """Convert a Hydra DictConfig to a plain dict with variables resolved."""
    return OmegaConf.to_container(cfg, resolve=True, throw_on_missing=True)  # type: ignore[return-value]


# %% ../../nbs/18_tutorials.end2end_hydra_cli.ipynb #bf17ba28
def run_train(cfg: DictConfig) -> dict[str, Any]:
    """Train an anomaly-detection model."""
    params = cfg_to_dict(cfg)
    config = FlexibleTrainingConfig(**params)
    return train_anomaly_model(config)


# %% ../../nbs/18_tutorials.end2end_hydra_cli.ipynb #98d3bf21
def run_infer(cfg: DictConfig) -> dict[str, Any]:
    """Run unified inference on image folder(s) or list file."""
    params = cfg_to_dict(cfg)
    return unified_inference(**params)


# %% ../../nbs/18_tutorials.end2end_hydra_cli.ipynb #a19f9c7b
def run_organize(cfg: DictConfig) -> dict[str, Any]:
    """Predict anomaly scores and organize images into threshold folders."""
    params = cfg_to_dict(cfg)
    return predict_and_organize_by_score(**params)


# %% ../../nbs/18_tutorials.end2end_hydra_cli.ipynb #1ca2d96d
def run_infer_organize(cfg: DictConfig) -> dict[str, Any]:
    """Unified inference + threshold folders + optional posters."""
    params = cfg_to_dict(cfg)
    return unified_inference_with_threshold_posters(**params)


# %% ../../nbs/18_tutorials.end2end_hydra_cli.ipynb #b3f511bc
def run_train_infer(cfg: DictConfig) -> dict[str, Any]:
    """Train a model, then run inference/posters from training results."""
    root = cfg_to_dict(cfg)
    train_params = root.get('train', root)
    infer_params = root.get('infer_after_training', {})

    training_results = run_train(OmegaConf.create(train_params))
    return run_inference_after_training(training_results, **infer_params)


# %% ../../nbs/18_tutorials.end2end_hydra_cli.ipynb #c772ddb3
def run_full(cfg: DictConfig) -> dict[str, Any]:
    """Train, then run unified inference with threshold organization."""
    root = cfg_to_dict(cfg)
    train_params = root['train']
    infer_params = root['infer_organize']

    training_results = run_train(OmegaConf.create(train_params))
    if not training_results.get('success', False):
        raise RuntimeError('Training failed; aborting full pipeline')

    export_paths = training_results.get('export_paths', {})
    model_path = export_paths.get('torch') or training_results.get('best_model_path')
    if model_path is None:
        raise RuntimeError('No model path in training results')

    infer_params = dict(infer_params)
    infer_params['model_path'] = str(model_path)
    return run_infer_organize(OmegaConf.create(infer_params))


# %% ../../nbs/18_tutorials.end2end_hydra_cli.ipynb #76b5fb5d
_CONF = str(Path(__file__).resolve().parent / 'conf')


# %% ../../nbs/18_tutorials.end2end_hydra_cli.ipynb #27614772
@hydra.main(version_base=None, config_path=_CONF, config_name='train')
def train_cli(cfg: DictConfig) -> None:
    """Train an anomaly-detection model."""
    result = run_train(cfg)
    print(result)


# %% ../../nbs/18_tutorials.end2end_hydra_cli.ipynb #f0f71082
@hydra.main(version_base=None, config_path=_CONF, config_name='infer')
def infer_cli(cfg: DictConfig) -> None:
    """Score images with unified inference."""
    result = run_infer(cfg)
    print(result)


# %% ../../nbs/18_tutorials.end2end_hydra_cli.ipynb #d057e7bf
@hydra.main(version_base=None, config_path=_CONF, config_name='organize')
def organize_cli(cfg: DictConfig) -> None:
    """Organize images by anomaly score."""
    result = run_organize(cfg)
    print(result)


# %% ../../nbs/18_tutorials.end2end_hydra_cli.ipynb #d588e24b
@hydra.main(version_base=None, config_path=_CONF, config_name='infer_organize')
def infer_organize_cli(cfg: DictConfig) -> None:
    """Inference + threshold folders + posters."""
    result = run_infer_organize(cfg)
    print(result)


# %% ../../nbs/18_tutorials.end2end_hydra_cli.ipynb #2cdf315f
@hydra.main(version_base=None, config_path=_CONF, config_name='train_infer')
def train_infer_cli(cfg: DictConfig) -> None:
    """Train, then inference/posters from training results."""
    result = run_train_infer(cfg)
    print(result)


# %% ../../nbs/18_tutorials.end2end_hydra_cli.ipynb #8828ee7a
@hydra.main(version_base=None, config_path=_CONF, config_name='full')
def full_cli(cfg: DictConfig) -> None:
    """Train, then unified inference with threshold organization."""
    result = run_full(cfg)
    print(result)

