"""Hydra-configured CLI entry points.

Docs: https://HasanGoni.github.io/vision_ad_tool/training.hyperparameter_hydra_cli.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/19_training.hyperparameter_hydra_cli.ipynb.

# %% auto #0
__all__ = ['run_hyperparam_search', 'hyperparam_search_cli']

# %% ../../nbs/19_training.hyperparameter_hydra_cli.ipynb #1f8fba23
from pathlib import Path
from typing import Any

import hydra
from omegaconf import DictConfig, OmegaConf

from .hyperparameter_search import diff_parameter_and_save_poster
from ..tutorials.end2end_cli import cfg_to_dict


# %% ../../nbs/19_training.hyperparameter_hydra_cli.ipynb #c54ec294
def run_hyperparam_search(cfg: DictConfig) -> dict[str, Any]:
    """Run hyperparameter grid search and save a comparison poster."""
    params = cfg_to_dict(cfg)
    figsize = params.get('figsize')
    if figsize is not None:
        params['figsize'] = tuple(figsize)
    return diff_parameter_and_save_poster(**params)


# %% ../../nbs/19_training.hyperparameter_hydra_cli.ipynb #44505fc9
_CONF = str(Path(__file__).resolve().parent.parent / 'tutorials' / 'conf')


# %% ../../nbs/19_training.hyperparameter_hydra_cli.ipynb #151ca993
@hydra.main(version_base=None, config_path=_CONF, config_name='hyperparam_search')
def hyperparam_search_cli(cfg: DictConfig) -> None:
    """Hyperparameter grid search + comparison poster."""
    result = run_hyperparam_search(cfg)
    print(result)

