# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vision_ad_tool',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/vision_ad_tool',
                'lib_path': 'vision_ad_tool'},
  'syms': {'vision_ad_tool.core': {'vision_ad_tool.core.foo': ('core.html#foo', 'vision_ad_tool/core.py')}}}
