"""Complete guide to fixing tiling issues and implementing tiling correctly with anomalib v2.0+"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/16_tiling_fix_and_implementation.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/16_tiling_fix_and_implementation.ipynb 3
import sys
import warnings
from pathlib import Path
from typing import Tuple, Optional, Dict, Any, List

# Core libraries
import numpy as np
import torch
from PIL import Image
import matplotlib.pyplot as plt

# Suppress warnings
warnings.filterwarnings('ignore')

# %% ../../nbs/16_tiling_fix_and_implementation.ipynb 7
# Correct imports for anomalib v2.0+
from anomalib import TaskType
from anomalib.data.image.folder import Folder
from anomalib.engine import Engine
from anomalib.models import Padim, Patchcore
from anomalib.callbacks import TilerConfigurationCallback  # Note: TilerConfigurationCallback, not TilingConfigurationCallback
from anomalib.deploy import ExportType

print("✅ Imports successful")
print(f"   Using: anomalib.callbacks.TilerConfigurationCallback")
print(f"   NOT: anomalib.callbacks.TilingConfigurationCallback (this is incorrect)")
