# @package _global_
# Train, then run_inference_after_training

train:
  data_root: ???
  class_name: anomaly_detection
  normal_dir: good
  abnormal_dir: bad
  model_name: padim
  backbone: resnet18
  max_epochs: 100
  save_path: ./models
  export_formats:
    - torch

infer_after_training:
  validation_images: ???
  test_images: null
  create_heatmaps: true
  poster_rows: 4
  poster_cols: 4
  output_folder: null
